### ISSUE TITLE
graphql-upload-client example

### ISSUE THREAD

**Issue by JipSterk** [benawad/typescript-nextjs-graphql-series#1]
could you use [graphql-upload-client](https://github.com/jaydenseric/apollo-upload-client) to implement a front end implementation for the backend you [created](https://github.com/benawad/type-graphql-series/tree/11_file_uploads) in combination with `formik`

**Comment by benawad** [comment]
Here's an example: https://github.com/benawad/apollo-upload-example/blob/master/src/App.js

You can store the file in formik.

Note the syntax for Dropzone has changed a little bit so make sure to consult the docs for it
